name:       nvds-lib
version:    0.2.0.0
license:    BSD3
author:     Noon van der Silk
maintainer: noonsilk@gmail.com
copyright:  2017 Noon van der Silk
category:   Web
extra-source-files:
    - README.md

dependencies:
    - base >= 4.7 && < 5
    - colour
    - containers
    - diagrams-lib
    - linear
    - optparse-applicative
    - palette
    - svg-tree

library:
    source-dirs:      src
    exposed-modules:  
        - Nvds.Svg
        - Nvds.Colours.ColourSets


executables:
    Colour-Sampler:
        dependencies:
            - diagrams
            - diagrams-cairo
            - split
            - nvds-lib

        source-dirs: bin
        main:        Main.hs

