name:                Vector-Field
version:             0.1.0.0
homepage:            https://github.com/silky/fashion/Vector-Field#readme
license:             BSD3
author:              Noon van der Silk
maintainer:          noonsilk@gmail.com
copyright:           Noon van der Silk
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - colour
  - diagrams
  - diagrams-cairo
  - diagrams-lib

executables:
  Vector-Field:
    source-dirs:      src
    main:             Main.hs
