name:                Scan-Lines
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/silky/Scan-Lines#readme
license:             BSD3
author:              Noon van der Silk
maintainer:          noonsilk@gmail.com
copyright:           Noon van der Silk
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - diagrams
  - diagrams-cairo
  - diagrams-lib

executables:
  Scan-Lines:
    source-dirs:      src
    main:             Main.hs
