resolver: lts-10.7
packages:
    - .
    - location    : ../nvds-lib
      extra-dep : True
extra-deps:
    - random-extras-0.19@sha256:52579ee8653b17d8b19fb54833ecbab8df47b6cf61a77c9614df0c3155441d29
