name:                Hense
version:             0.1.0.0
homepage:            https://github.com/silky/fashion/Hense#readme
license:             BSD3
author:              Noon van der Silk
maintainer:          noonsilk@gmail.com
copyright:           Noon van der Silk
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - diagrams
  - diagrams-cairo
  - diagrams-core
  - diagrams-lib
  - lens
  - linear
  - nvds-lib
  - random
  - random-fu
  - random-source

executables:
  Hense:
    source-dirs:      src
    main:             Main.hs
