name:                Wave-Axis
version:             0.1.0.0
homepage:            https://github.com/silky/fashion/Wave-Axis#readme
license:             BSD3
author:              Noon van der Silk
maintainer:          noonsilk@gmail.com
copyright:           Noon van der Silk
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - diagrams
  - diagrams-cairo
  - diagrams-lib

library:
  source-dirs: src
  exposed-modules:
    - Nvds.Designs.WaveAxis

executables:
  Wave-Axis:
    dependencies:
      - Wave-Axis

    source-dirs:      src
    main:             Main.hs
