name:                Sketchy-Depth
version:             0.1.0.0
homepage:            https://github.com/silky/fashion/Sketchy-Depth#readme
license:             BSD3
author:              Noon van der Silk
maintainer:          noonsilk@gmail.com
copyright:           Noon van der Silk
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - diagrams
  - diagrams-cairo
  - diagrams-lib
  - filepath
  - string-conv
  - split
  - vector

library:
  source-dirs: src
  exposed-modules:
    - Nvds.Designs.SketchyDepths

executables:
  Sketchy-Depth:
    dependencies:
      - Sketchy-Depth

    source-dirs:      src
    main:             Main.hs
